title: Map Drawing SDK Documentation
theme: just-the-docs
logo: null
color_scheme: light

# Set base path (REPO-NAME)
baseurl: "/25B-10221-Advanced_Seminar_in_Mobile_Development"

# Enable search box (optional)
search_enabled: true
