title: Map Drawing SDK Documentation
description: Documentation for API, Android SDK, and example app
remote_theme: just-the-docs/just-the-docs

# Enable clean URLs
permalink: pretty

# Sidebar
collections:
  pages:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    pages:
      sidebar:
        nav: "docs/_sidebar.yml"
